---
apiVersion: v1
kind: Service
metadata:
  name: haskell
  labels:
    app: haskell
spec:
  type: LoadBalancer
  selector:
    app: haskell
  ports:
  - name: webserve-http
    protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haskell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haskell
  template:
    metadata:
      labels:
        app: haskell
    spec:
      containers:
      - name: haskell
        imagePullPolicy: IfNotPresent
        image: localhost:32000/postgrest/postgrest:registry
        env:
          - name: DB_URI
            valueFrom:
              secretKeyRef:
                name: itcsa-haskell-key-75h58mk57t
                key: db-uri
          - name: DB_SCHEMA
            valueFrom:
              secretKeyRef:
                name: itcsa-haskell-key-75h58mk57t
                key: db-schema
          - name: DB_ANON_ROLE
            valueFrom:
              secretKeyRef:
                name: itcsa-haskell-key-75h58mk57t
                key: db-anon-role
          - name: POSTGRES_HOST
            value: postgres
          - name: POSTGRES_PORT
            value: "postgres"
          - name: POSTGRES_DATABASE
            valueFrom:
              secretKeyRef:
                name: itcsa-postgres-key-9t6f84kgg5
                key: database
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: itcsa-postgres-key-9t6f84kgg5
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: itcsa-postgres-key-9t6f84kgg5
                key: password
        ports:
        - containerPort: 3000
          name: webserve-http
      nodeSelector:
        nodetype: database-node